# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Jari's Playground
site_url: https://jari27.github.io
repo_url: https://github.com/Jari27/jari27.github.io
repo_name: jari27/jari27.github.io
theme:
  name: 'material'
  features:
    - navigation.sections
    - navigation.path
    - navigation.top
    - toc.integrate
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: default)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github # github icon
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jari-meevis/
markdown_extensions:
  - admonition
  - pymdownx.superfences  # nesting of blocks/admonitions/etc
  - pymdownx.details      # collapsible admonitions
  - pymdownx.highlight:   # code highlighting
      use_pygments: true
      # auto_title: true
      line_spans: __span
