[project]
name = "jari27-github-io"
version = "0.1.0"
description = "A playground for mkdocs-material"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs-material>=9.6.7",
]

[dependency-groups]
dev = []
